// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerReturn4Int.proto

#ifndef PROTOBUF_ServerReturn4Int_2eproto__INCLUDED
#define PROTOBUF_ServerReturn4Int_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ServerReturn {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ServerReturn4Int_2eproto();
void protobuf_AssignDesc_ServerReturn4Int_2eproto();
void protobuf_ShutdownFile_ServerReturn4Int_2eproto();

class ServerFourInt;

// ===================================================================

class ServerFourInt : public ::google::protobuf::Message {
 public:
  ServerFourInt();
  virtual ~ServerFourInt();

  ServerFourInt(const ServerFourInt& from);

  inline ServerFourInt& operator=(const ServerFourInt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerFourInt& default_instance();

  void Swap(ServerFourInt* other);

  // implements Message ----------------------------------------------

  ServerFourInt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerFourInt& from);
  void MergeFrom(const ServerFourInt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 retf = 1;
  inline bool has_retf() const;
  inline void clear_retf();
  static const int kRetfFieldNumber = 1;
  inline ::google::protobuf::int64 retf() const;
  inline void set_retf(::google::protobuf::int64 value);

  // optional int64 rets = 2 [default = 0];
  inline bool has_rets() const;
  inline void clear_rets();
  static const int kRetsFieldNumber = 2;
  inline ::google::protobuf::int64 rets() const;
  inline void set_rets(::google::protobuf::int64 value);

  // optional int64 rett = 3 [default = 0];
  inline bool has_rett() const;
  inline void clear_rett();
  static const int kRettFieldNumber = 3;
  inline ::google::protobuf::int64 rett() const;
  inline void set_rett(::google::protobuf::int64 value);

  // optional int64 retfo = 4 [default = 0];
  inline bool has_retfo() const;
  inline void clear_retfo();
  static const int kRetfoFieldNumber = 4;
  inline ::google::protobuf::int64 retfo() const;
  inline void set_retfo(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:ServerReturn.ServerFourInt)
 private:
  inline void set_has_retf();
  inline void clear_has_retf();
  inline void set_has_rets();
  inline void clear_has_rets();
  inline void set_has_rett();
  inline void clear_has_rett();
  inline void set_has_retfo();
  inline void clear_has_retfo();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 retf_;
  ::google::protobuf::int64 rets_;
  ::google::protobuf::int64 rett_;
  ::google::protobuf::int64 retfo_;
  friend void  protobuf_AddDesc_ServerReturn4Int_2eproto();
  friend void protobuf_AssignDesc_ServerReturn4Int_2eproto();
  friend void protobuf_ShutdownFile_ServerReturn4Int_2eproto();

  void InitAsDefaultInstance();
  static ServerFourInt* default_instance_;
};
// ===================================================================


// ===================================================================

// ServerFourInt

// required int64 retf = 1;
inline bool ServerFourInt::has_retf() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerFourInt::set_has_retf() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerFourInt::clear_has_retf() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerFourInt::clear_retf() {
  retf_ = GOOGLE_LONGLONG(0);
  clear_has_retf();
}
inline ::google::protobuf::int64 ServerFourInt::retf() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerFourInt.retf)
  return retf_;
}
inline void ServerFourInt::set_retf(::google::protobuf::int64 value) {
  set_has_retf();
  retf_ = value;
  // @@protoc_insertion_point(field_set:ServerReturn.ServerFourInt.retf)
}

// optional int64 rets = 2 [default = 0];
inline bool ServerFourInt::has_rets() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ServerFourInt::set_has_rets() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ServerFourInt::clear_has_rets() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ServerFourInt::clear_rets() {
  rets_ = GOOGLE_LONGLONG(0);
  clear_has_rets();
}
inline ::google::protobuf::int64 ServerFourInt::rets() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerFourInt.rets)
  return rets_;
}
inline void ServerFourInt::set_rets(::google::protobuf::int64 value) {
  set_has_rets();
  rets_ = value;
  // @@protoc_insertion_point(field_set:ServerReturn.ServerFourInt.rets)
}

// optional int64 rett = 3 [default = 0];
inline bool ServerFourInt::has_rett() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ServerFourInt::set_has_rett() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ServerFourInt::clear_has_rett() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ServerFourInt::clear_rett() {
  rett_ = GOOGLE_LONGLONG(0);
  clear_has_rett();
}
inline ::google::protobuf::int64 ServerFourInt::rett() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerFourInt.rett)
  return rett_;
}
inline void ServerFourInt::set_rett(::google::protobuf::int64 value) {
  set_has_rett();
  rett_ = value;
  // @@protoc_insertion_point(field_set:ServerReturn.ServerFourInt.rett)
}

// optional int64 retfo = 4 [default = 0];
inline bool ServerFourInt::has_retfo() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ServerFourInt::set_has_retfo() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ServerFourInt::clear_has_retfo() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ServerFourInt::clear_retfo() {
  retfo_ = GOOGLE_LONGLONG(0);
  clear_has_retfo();
}
inline ::google::protobuf::int64 ServerFourInt::retfo() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerFourInt.retfo)
  return retfo_;
}
inline void ServerFourInt::set_retfo(::google::protobuf::int64 value) {
  set_has_retfo();
  retfo_ = value;
  // @@protoc_insertion_point(field_set:ServerReturn.ServerFourInt.retfo)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ServerReturn

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerReturn4Int_2eproto__INCLUDED
