// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerReturnInt.proto

#ifndef PROTOBUF_ServerReturnInt_2eproto__INCLUDED
#define PROTOBUF_ServerReturnInt_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ServerReturn {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ServerReturnInt_2eproto();
void protobuf_AssignDesc_ServerReturnInt_2eproto();
void protobuf_ShutdownFile_ServerReturnInt_2eproto();

class ServerRetInt;
class ServerRetIntArray;
class ServerRetInt32Array;
class ServerDoubleIntArray;
class ServerResultInt;

// ===================================================================

class ServerRetInt : public ::google::protobuf::Message {
 public:
  ServerRetInt();
  virtual ~ServerRetInt();

  ServerRetInt(const ServerRetInt& from);

  inline ServerRetInt& operator=(const ServerRetInt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerRetInt& default_instance();

  void Swap(ServerRetInt* other);

  // implements Message ----------------------------------------------

  ServerRetInt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerRetInt& from);
  void MergeFrom(const ServerRetInt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int64 ret() const;
  inline void set_ret(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:ServerReturn.ServerRetInt)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 ret_;
  friend void  protobuf_AddDesc_ServerReturnInt_2eproto();
  friend void protobuf_AssignDesc_ServerReturnInt_2eproto();
  friend void protobuf_ShutdownFile_ServerReturnInt_2eproto();

  void InitAsDefaultInstance();
  static ServerRetInt* default_instance_;
};
// -------------------------------------------------------------------

class ServerRetIntArray : public ::google::protobuf::Message {
 public:
  ServerRetIntArray();
  virtual ~ServerRetIntArray();

  ServerRetIntArray(const ServerRetIntArray& from);

  inline ServerRetIntArray& operator=(const ServerRetIntArray& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerRetIntArray& default_instance();

  void Swap(ServerRetIntArray* other);

  // implements Message ----------------------------------------------

  ServerRetIntArray* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerRetIntArray& from);
  void MergeFrom(const ServerRetIntArray& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 ret = 1;
  inline int ret_size() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int64 ret(int index) const;
  inline void set_ret(int index, ::google::protobuf::int64 value);
  inline void add_ret(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      ret() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_ret();

  // @@protoc_insertion_point(class_scope:ServerReturn.ServerRetIntArray)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > ret_;
  friend void  protobuf_AddDesc_ServerReturnInt_2eproto();
  friend void protobuf_AssignDesc_ServerReturnInt_2eproto();
  friend void protobuf_ShutdownFile_ServerReturnInt_2eproto();

  void InitAsDefaultInstance();
  static ServerRetIntArray* default_instance_;
};
// -------------------------------------------------------------------

class ServerRetInt32Array : public ::google::protobuf::Message {
 public:
  ServerRetInt32Array();
  virtual ~ServerRetInt32Array();

  ServerRetInt32Array(const ServerRetInt32Array& from);

  inline ServerRetInt32Array& operator=(const ServerRetInt32Array& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerRetInt32Array& default_instance();

  void Swap(ServerRetInt32Array* other);

  // implements Message ----------------------------------------------

  ServerRetInt32Array* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerRetInt32Array& from);
  void MergeFrom(const ServerRetInt32Array& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 ret = 1;
  inline int ret_size() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int32 ret(int index) const;
  inline void set_ret(int index, ::google::protobuf::int32 value);
  inline void add_ret(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      ret() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_ret();

  // @@protoc_insertion_point(class_scope:ServerReturn.ServerRetInt32Array)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > ret_;
  friend void  protobuf_AddDesc_ServerReturnInt_2eproto();
  friend void protobuf_AssignDesc_ServerReturnInt_2eproto();
  friend void protobuf_ShutdownFile_ServerReturnInt_2eproto();

  void InitAsDefaultInstance();
  static ServerRetInt32Array* default_instance_;
};
// -------------------------------------------------------------------

class ServerDoubleIntArray : public ::google::protobuf::Message {
 public:
  ServerDoubleIntArray();
  virtual ~ServerDoubleIntArray();

  ServerDoubleIntArray(const ServerDoubleIntArray& from);

  inline ServerDoubleIntArray& operator=(const ServerDoubleIntArray& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerDoubleIntArray& default_instance();

  void Swap(ServerDoubleIntArray* other);

  // implements Message ----------------------------------------------

  ServerDoubleIntArray* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerDoubleIntArray& from);
  void MergeFrom(const ServerDoubleIntArray& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 retf = 1;
  inline bool has_retf() const;
  inline void clear_retf();
  static const int kRetfFieldNumber = 1;
  inline ::google::protobuf::int64 retf() const;
  inline void set_retf(::google::protobuf::int64 value);

  // repeated int64 rets = 2;
  inline int rets_size() const;
  inline void clear_rets();
  static const int kRetsFieldNumber = 2;
  inline ::google::protobuf::int64 rets(int index) const;
  inline void set_rets(int index, ::google::protobuf::int64 value);
  inline void add_rets(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      rets() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_rets();

  // @@protoc_insertion_point(class_scope:ServerReturn.ServerDoubleIntArray)
 private:
  inline void set_has_retf();
  inline void clear_has_retf();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 retf_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > rets_;
  friend void  protobuf_AddDesc_ServerReturnInt_2eproto();
  friend void protobuf_AssignDesc_ServerReturnInt_2eproto();
  friend void protobuf_ShutdownFile_ServerReturnInt_2eproto();

  void InitAsDefaultInstance();
  static ServerDoubleIntArray* default_instance_;
};
// -------------------------------------------------------------------

class ServerResultInt : public ::google::protobuf::Message {
 public:
  ServerResultInt();
  virtual ~ServerResultInt();

  ServerResultInt(const ServerResultInt& from);

  inline ServerResultInt& operator=(const ServerResultInt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerResultInt& default_instance();

  void Swap(ServerResultInt* other);

  // implements Message ----------------------------------------------

  ServerResultInt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerResultInt& from);
  void MergeFrom(const ServerResultInt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ServerReturn.ServerResultInt)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 ret_;
  friend void  protobuf_AddDesc_ServerReturnInt_2eproto();
  friend void protobuf_AssignDesc_ServerReturnInt_2eproto();
  friend void protobuf_ShutdownFile_ServerReturnInt_2eproto();

  void InitAsDefaultInstance();
  static ServerResultInt* default_instance_;
};
// ===================================================================


// ===================================================================

// ServerRetInt

// required int64 ret = 1;
inline bool ServerRetInt::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerRetInt::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerRetInt::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerRetInt::clear_ret() {
  ret_ = GOOGLE_LONGLONG(0);
  clear_has_ret();
}
inline ::google::protobuf::int64 ServerRetInt::ret() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerRetInt.ret)
  return ret_;
}
inline void ServerRetInt::set_ret(::google::protobuf::int64 value) {
  set_has_ret();
  ret_ = value;
  // @@protoc_insertion_point(field_set:ServerReturn.ServerRetInt.ret)
}

// -------------------------------------------------------------------

// ServerRetIntArray

// repeated int64 ret = 1;
inline int ServerRetIntArray::ret_size() const {
  return ret_.size();
}
inline void ServerRetIntArray::clear_ret() {
  ret_.Clear();
}
inline ::google::protobuf::int64 ServerRetIntArray::ret(int index) const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerRetIntArray.ret)
  return ret_.Get(index);
}
inline void ServerRetIntArray::set_ret(int index, ::google::protobuf::int64 value) {
  ret_.Set(index, value);
  // @@protoc_insertion_point(field_set:ServerReturn.ServerRetIntArray.ret)
}
inline void ServerRetIntArray::add_ret(::google::protobuf::int64 value) {
  ret_.Add(value);
  // @@protoc_insertion_point(field_add:ServerReturn.ServerRetIntArray.ret)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
ServerRetIntArray::ret() const {
  // @@protoc_insertion_point(field_list:ServerReturn.ServerRetIntArray.ret)
  return ret_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
ServerRetIntArray::mutable_ret() {
  // @@protoc_insertion_point(field_mutable_list:ServerReturn.ServerRetIntArray.ret)
  return &ret_;
}

// -------------------------------------------------------------------

// ServerRetInt32Array

// repeated int32 ret = 1;
inline int ServerRetInt32Array::ret_size() const {
  return ret_.size();
}
inline void ServerRetInt32Array::clear_ret() {
  ret_.Clear();
}
inline ::google::protobuf::int32 ServerRetInt32Array::ret(int index) const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerRetInt32Array.ret)
  return ret_.Get(index);
}
inline void ServerRetInt32Array::set_ret(int index, ::google::protobuf::int32 value) {
  ret_.Set(index, value);
  // @@protoc_insertion_point(field_set:ServerReturn.ServerRetInt32Array.ret)
}
inline void ServerRetInt32Array::add_ret(::google::protobuf::int32 value) {
  ret_.Add(value);
  // @@protoc_insertion_point(field_add:ServerReturn.ServerRetInt32Array.ret)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ServerRetInt32Array::ret() const {
  // @@protoc_insertion_point(field_list:ServerReturn.ServerRetInt32Array.ret)
  return ret_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ServerRetInt32Array::mutable_ret() {
  // @@protoc_insertion_point(field_mutable_list:ServerReturn.ServerRetInt32Array.ret)
  return &ret_;
}

// -------------------------------------------------------------------

// ServerDoubleIntArray

// required int64 retf = 1;
inline bool ServerDoubleIntArray::has_retf() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerDoubleIntArray::set_has_retf() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerDoubleIntArray::clear_has_retf() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerDoubleIntArray::clear_retf() {
  retf_ = GOOGLE_LONGLONG(0);
  clear_has_retf();
}
inline ::google::protobuf::int64 ServerDoubleIntArray::retf() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerDoubleIntArray.retf)
  return retf_;
}
inline void ServerDoubleIntArray::set_retf(::google::protobuf::int64 value) {
  set_has_retf();
  retf_ = value;
  // @@protoc_insertion_point(field_set:ServerReturn.ServerDoubleIntArray.retf)
}

// repeated int64 rets = 2;
inline int ServerDoubleIntArray::rets_size() const {
  return rets_.size();
}
inline void ServerDoubleIntArray::clear_rets() {
  rets_.Clear();
}
inline ::google::protobuf::int64 ServerDoubleIntArray::rets(int index) const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerDoubleIntArray.rets)
  return rets_.Get(index);
}
inline void ServerDoubleIntArray::set_rets(int index, ::google::protobuf::int64 value) {
  rets_.Set(index, value);
  // @@protoc_insertion_point(field_set:ServerReturn.ServerDoubleIntArray.rets)
}
inline void ServerDoubleIntArray::add_rets(::google::protobuf::int64 value) {
  rets_.Add(value);
  // @@protoc_insertion_point(field_add:ServerReturn.ServerDoubleIntArray.rets)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
ServerDoubleIntArray::rets() const {
  // @@protoc_insertion_point(field_list:ServerReturn.ServerDoubleIntArray.rets)
  return rets_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
ServerDoubleIntArray::mutable_rets() {
  // @@protoc_insertion_point(field_mutable_list:ServerReturn.ServerDoubleIntArray.rets)
  return &rets_;
}

// -------------------------------------------------------------------

// ServerResultInt

// required int32 ret = 1;
inline bool ServerResultInt::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerResultInt::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerResultInt::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerResultInt::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 ServerResultInt::ret() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerResultInt.ret)
  return ret_;
}
inline void ServerResultInt::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
  // @@protoc_insertion_point(field_set:ServerReturn.ServerResultInt.ret)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ServerReturn

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerReturnInt_2eproto__INCLUDED
