// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerReturnChar.proto

#ifndef PROTOBUF_ServerReturnChar_2eproto__INCLUDED
#define PROTOBUF_ServerReturnChar_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ServerReturn {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ServerReturnChar_2eproto();
void protobuf_AssignDesc_ServerReturnChar_2eproto();
void protobuf_ShutdownFile_ServerReturnChar_2eproto();

class ServerRetChar;

// ===================================================================

class ServerRetChar : public ::google::protobuf::Message {
 public:
  ServerRetChar();
  virtual ~ServerRetChar();

  ServerRetChar(const ServerRetChar& from);

  inline ServerRetChar& operator=(const ServerRetChar& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerRetChar& default_instance();

  void Swap(ServerRetChar* other);

  // implements Message ----------------------------------------------

  ServerRetChar* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerRetChar& from);
  void MergeFrom(const ServerRetChar& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string ret = 1;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 1;
  inline const ::std::string& ret() const;
  inline void set_ret(const ::std::string& value);
  inline void set_ret(const char* value);
  inline void set_ret(const char* value, size_t size);
  inline ::std::string* mutable_ret();
  inline ::std::string* release_ret();
  inline void set_allocated_ret(::std::string* ret);

  // @@protoc_insertion_point(class_scope:ServerReturn.ServerRetChar)
 private:
  inline void set_has_ret();
  inline void clear_has_ret();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* ret_;
  friend void  protobuf_AddDesc_ServerReturnChar_2eproto();
  friend void protobuf_AssignDesc_ServerReturnChar_2eproto();
  friend void protobuf_ShutdownFile_ServerReturnChar_2eproto();

  void InitAsDefaultInstance();
  static ServerRetChar* default_instance_;
};
// ===================================================================


// ===================================================================

// ServerRetChar

// required string ret = 1;
inline bool ServerRetChar::has_ret() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerRetChar::set_has_ret() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerRetChar::clear_has_ret() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerRetChar::clear_ret() {
  if (ret_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_->clear();
  }
  clear_has_ret();
}
inline const ::std::string& ServerRetChar::ret() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerRetChar.ret)
  return *ret_;
}
inline void ServerRetChar::set_ret(const ::std::string& value) {
  set_has_ret();
  if (ret_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_ = new ::std::string;
  }
  ret_->assign(value);
  // @@protoc_insertion_point(field_set:ServerReturn.ServerRetChar.ret)
}
inline void ServerRetChar::set_ret(const char* value) {
  set_has_ret();
  if (ret_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_ = new ::std::string;
  }
  ret_->assign(value);
  // @@protoc_insertion_point(field_set_char:ServerReturn.ServerRetChar.ret)
}
inline void ServerRetChar::set_ret(const char* value, size_t size) {
  set_has_ret();
  if (ret_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_ = new ::std::string;
  }
  ret_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ServerReturn.ServerRetChar.ret)
}
inline ::std::string* ServerRetChar::mutable_ret() {
  set_has_ret();
  if (ret_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ret_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:ServerReturn.ServerRetChar.ret)
  return ret_;
}
inline ::std::string* ServerRetChar::release_ret() {
  clear_has_ret();
  if (ret_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = ret_;
    ret_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ServerRetChar::set_allocated_ret(::std::string* ret) {
  if (ret_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ret_;
  }
  if (ret) {
    set_has_ret();
    ret_ = ret;
  } else {
    clear_has_ret();
    ret_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:ServerReturn.ServerRetChar.ret)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ServerReturn

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerReturnChar_2eproto__INCLUDED
