// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerReturn5Int.proto

#ifndef PROTOBUF_ServerReturn5Int_2eproto__INCLUDED
#define PROTOBUF_ServerReturn5Int_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ServerReturn {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ServerReturn5Int_2eproto();
void protobuf_AssignDesc_ServerReturn5Int_2eproto();
void protobuf_ShutdownFile_ServerReturn5Int_2eproto();

class ServerFiveInt;

// ===================================================================

class ServerFiveInt : public ::google::protobuf::Message {
 public:
  ServerFiveInt();
  virtual ~ServerFiveInt();

  ServerFiveInt(const ServerFiveInt& from);

  inline ServerFiveInt& operator=(const ServerFiveInt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerFiveInt& default_instance();

  void Swap(ServerFiveInt* other);

  // implements Message ----------------------------------------------

  ServerFiveInt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerFiveInt& from);
  void MergeFrom(const ServerFiveInt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 retf = 1;
  inline bool has_retf() const;
  inline void clear_retf();
  static const int kRetfFieldNumber = 1;
  inline ::google::protobuf::int64 retf() const;
  inline void set_retf(::google::protobuf::int64 value);

  // required int64 rets = 2;
  inline bool has_rets() const;
  inline void clear_rets();
  static const int kRetsFieldNumber = 2;
  inline ::google::protobuf::int64 rets() const;
  inline void set_rets(::google::protobuf::int64 value);

  // optional int64 oldrets = 3;
  inline bool has_oldrets() const;
  inline void clear_oldrets();
  static const int kOldretsFieldNumber = 3;
  inline ::google::protobuf::int64 oldrets() const;
  inline void set_oldrets(::google::protobuf::int64 value);

  // optional int64 oldXPos = 4;
  inline bool has_oldxpos() const;
  inline void clear_oldxpos();
  static const int kOldXPosFieldNumber = 4;
  inline ::google::protobuf::int64 oldxpos() const;
  inline void set_oldxpos(::google::protobuf::int64 value);

  // optional int64 oldYPos = 5;
  inline bool has_oldypos() const;
  inline void clear_oldypos();
  static const int kOldYPosFieldNumber = 5;
  inline ::google::protobuf::int64 oldypos() const;
  inline void set_oldypos(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:ServerReturn.ServerFiveInt)
 private:
  inline void set_has_retf();
  inline void clear_has_retf();
  inline void set_has_rets();
  inline void clear_has_rets();
  inline void set_has_oldrets();
  inline void clear_has_oldrets();
  inline void set_has_oldxpos();
  inline void clear_has_oldxpos();
  inline void set_has_oldypos();
  inline void clear_has_oldypos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 retf_;
  ::google::protobuf::int64 rets_;
  ::google::protobuf::int64 oldrets_;
  ::google::protobuf::int64 oldxpos_;
  ::google::protobuf::int64 oldypos_;
  friend void  protobuf_AddDesc_ServerReturn5Int_2eproto();
  friend void protobuf_AssignDesc_ServerReturn5Int_2eproto();
  friend void protobuf_ShutdownFile_ServerReturn5Int_2eproto();

  void InitAsDefaultInstance();
  static ServerFiveInt* default_instance_;
};
// ===================================================================


// ===================================================================

// ServerFiveInt

// required int64 retf = 1;
inline bool ServerFiveInt::has_retf() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerFiveInt::set_has_retf() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerFiveInt::clear_has_retf() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerFiveInt::clear_retf() {
  retf_ = GOOGLE_LONGLONG(0);
  clear_has_retf();
}
inline ::google::protobuf::int64 ServerFiveInt::retf() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerFiveInt.retf)
  return retf_;
}
inline void ServerFiveInt::set_retf(::google::protobuf::int64 value) {
  set_has_retf();
  retf_ = value;
  // @@protoc_insertion_point(field_set:ServerReturn.ServerFiveInt.retf)
}

// required int64 rets = 2;
inline bool ServerFiveInt::has_rets() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ServerFiveInt::set_has_rets() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ServerFiveInt::clear_has_rets() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ServerFiveInt::clear_rets() {
  rets_ = GOOGLE_LONGLONG(0);
  clear_has_rets();
}
inline ::google::protobuf::int64 ServerFiveInt::rets() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerFiveInt.rets)
  return rets_;
}
inline void ServerFiveInt::set_rets(::google::protobuf::int64 value) {
  set_has_rets();
  rets_ = value;
  // @@protoc_insertion_point(field_set:ServerReturn.ServerFiveInt.rets)
}

// optional int64 oldrets = 3;
inline bool ServerFiveInt::has_oldrets() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ServerFiveInt::set_has_oldrets() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ServerFiveInt::clear_has_oldrets() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ServerFiveInt::clear_oldrets() {
  oldrets_ = GOOGLE_LONGLONG(0);
  clear_has_oldrets();
}
inline ::google::protobuf::int64 ServerFiveInt::oldrets() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerFiveInt.oldrets)
  return oldrets_;
}
inline void ServerFiveInt::set_oldrets(::google::protobuf::int64 value) {
  set_has_oldrets();
  oldrets_ = value;
  // @@protoc_insertion_point(field_set:ServerReturn.ServerFiveInt.oldrets)
}

// optional int64 oldXPos = 4;
inline bool ServerFiveInt::has_oldxpos() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ServerFiveInt::set_has_oldxpos() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ServerFiveInt::clear_has_oldxpos() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ServerFiveInt::clear_oldxpos() {
  oldxpos_ = GOOGLE_LONGLONG(0);
  clear_has_oldxpos();
}
inline ::google::protobuf::int64 ServerFiveInt::oldxpos() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerFiveInt.oldXPos)
  return oldxpos_;
}
inline void ServerFiveInt::set_oldxpos(::google::protobuf::int64 value) {
  set_has_oldxpos();
  oldxpos_ = value;
  // @@protoc_insertion_point(field_set:ServerReturn.ServerFiveInt.oldXPos)
}

// optional int64 oldYPos = 5;
inline bool ServerFiveInt::has_oldypos() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ServerFiveInt::set_has_oldypos() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ServerFiveInt::clear_has_oldypos() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ServerFiveInt::clear_oldypos() {
  oldypos_ = GOOGLE_LONGLONG(0);
  clear_has_oldypos();
}
inline ::google::protobuf::int64 ServerFiveInt::oldypos() const {
  // @@protoc_insertion_point(field_get:ServerReturn.ServerFiveInt.oldYPos)
  return oldypos_;
}
inline void ServerFiveInt::set_oldypos(::google::protobuf::int64 value) {
  set_has_oldypos();
  oldypos_ = value;
  // @@protoc_insertion_point(field_set:ServerReturn.ServerFiveInt.oldYPos)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ServerReturn

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerReturn5Int_2eproto__INCLUDED
