// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerReturn5Int.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ServerReturn5Int.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ServerReturn {

namespace {

const ::google::protobuf::Descriptor* ServerFiveInt_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ServerFiveInt_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ServerReturn5Int_2eproto() {
  protobuf_AddDesc_ServerReturn5Int_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ServerReturn5Int.proto");
  GOOGLE_CHECK(file != NULL);
  ServerFiveInt_descriptor_ = file->message_type(0);
  static const int ServerFiveInt_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFiveInt, retf_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFiveInt, rets_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFiveInt, oldrets_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFiveInt, oldxpos_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFiveInt, oldypos_),
  };
  ServerFiveInt_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ServerFiveInt_descriptor_,
      ServerFiveInt::default_instance_,
      ServerFiveInt_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFiveInt, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFiveInt, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ServerFiveInt));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ServerReturn5Int_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ServerFiveInt_descriptor_, &ServerFiveInt::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ServerReturn5Int_2eproto() {
  delete ServerFiveInt::default_instance_;
  delete ServerFiveInt_reflection_;
}

void protobuf_AddDesc_ServerReturn5Int_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026ServerReturn5Int.proto\022\014ServerReturn\"^"
    "\n\rServerFiveInt\022\014\n\004retf\030\001 \002(\003\022\014\n\004rets\030\002 "
    "\002(\003\022\017\n\007oldrets\030\003 \001(\003\022\017\n\007oldXPos\030\004 \001(\003\022\017\n"
    "\007oldYPos\030\005 \001(\003", 134);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ServerReturn5Int.proto", &protobuf_RegisterTypes);
  ServerFiveInt::default_instance_ = new ServerFiveInt();
  ServerFiveInt::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ServerReturn5Int_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ServerReturn5Int_2eproto {
  StaticDescriptorInitializer_ServerReturn5Int_2eproto() {
    protobuf_AddDesc_ServerReturn5Int_2eproto();
  }
} static_descriptor_initializer_ServerReturn5Int_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ServerFiveInt::kRetfFieldNumber;
const int ServerFiveInt::kRetsFieldNumber;
const int ServerFiveInt::kOldretsFieldNumber;
const int ServerFiveInt::kOldXPosFieldNumber;
const int ServerFiveInt::kOldYPosFieldNumber;
#endif  // !_MSC_VER

ServerFiveInt::ServerFiveInt()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ServerReturn.ServerFiveInt)
}

void ServerFiveInt::InitAsDefaultInstance() {
}

ServerFiveInt::ServerFiveInt(const ServerFiveInt& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ServerReturn.ServerFiveInt)
}

void ServerFiveInt::SharedCtor() {
  _cached_size_ = 0;
  retf_ = GOOGLE_LONGLONG(0);
  rets_ = GOOGLE_LONGLONG(0);
  oldrets_ = GOOGLE_LONGLONG(0);
  oldxpos_ = GOOGLE_LONGLONG(0);
  oldypos_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ServerFiveInt::~ServerFiveInt() {
  // @@protoc_insertion_point(destructor:ServerReturn.ServerFiveInt)
  SharedDtor();
}

void ServerFiveInt::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ServerFiveInt::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ServerFiveInt::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ServerFiveInt_descriptor_;
}

const ServerFiveInt& ServerFiveInt::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ServerReturn5Int_2eproto();
  return *default_instance_;
}

ServerFiveInt* ServerFiveInt::default_instance_ = NULL;

ServerFiveInt* ServerFiveInt::New() const {
  return new ServerFiveInt;
}

void ServerFiveInt::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<ServerFiveInt*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 31) {
    ZR_(retf_, oldypos_);
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ServerFiveInt::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ServerReturn.ServerFiveInt)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 retf = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &retf_)));
          set_has_retf();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_rets;
        break;
      }

      // required int64 rets = 2;
      case 2: {
        if (tag == 16) {
         parse_rets:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &rets_)));
          set_has_rets();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_oldrets;
        break;
      }

      // optional int64 oldrets = 3;
      case 3: {
        if (tag == 24) {
         parse_oldrets:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &oldrets_)));
          set_has_oldrets();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_oldXPos;
        break;
      }

      // optional int64 oldXPos = 4;
      case 4: {
        if (tag == 32) {
         parse_oldXPos:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &oldxpos_)));
          set_has_oldxpos();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_oldYPos;
        break;
      }

      // optional int64 oldYPos = 5;
      case 5: {
        if (tag == 40) {
         parse_oldYPos:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &oldypos_)));
          set_has_oldypos();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ServerReturn.ServerFiveInt)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ServerReturn.ServerFiveInt)
  return false;
#undef DO_
}

void ServerFiveInt::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ServerReturn.ServerFiveInt)
  // required int64 retf = 1;
  if (has_retf()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->retf(), output);
  }

  // required int64 rets = 2;
  if (has_rets()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->rets(), output);
  }

  // optional int64 oldrets = 3;
  if (has_oldrets()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->oldrets(), output);
  }

  // optional int64 oldXPos = 4;
  if (has_oldxpos()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->oldxpos(), output);
  }

  // optional int64 oldYPos = 5;
  if (has_oldypos()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->oldypos(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ServerReturn.ServerFiveInt)
}

::google::protobuf::uint8* ServerFiveInt::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ServerReturn.ServerFiveInt)
  // required int64 retf = 1;
  if (has_retf()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->retf(), target);
  }

  // required int64 rets = 2;
  if (has_rets()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->rets(), target);
  }

  // optional int64 oldrets = 3;
  if (has_oldrets()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->oldrets(), target);
  }

  // optional int64 oldXPos = 4;
  if (has_oldxpos()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->oldxpos(), target);
  }

  // optional int64 oldYPos = 5;
  if (has_oldypos()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->oldypos(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ServerReturn.ServerFiveInt)
  return target;
}

int ServerFiveInt::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 retf = 1;
    if (has_retf()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->retf());
    }

    // required int64 rets = 2;
    if (has_rets()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->rets());
    }

    // optional int64 oldrets = 3;
    if (has_oldrets()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->oldrets());
    }

    // optional int64 oldXPos = 4;
    if (has_oldxpos()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->oldxpos());
    }

    // optional int64 oldYPos = 5;
    if (has_oldypos()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->oldypos());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ServerFiveInt::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ServerFiveInt* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ServerFiveInt*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ServerFiveInt::MergeFrom(const ServerFiveInt& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_retf()) {
      set_retf(from.retf());
    }
    if (from.has_rets()) {
      set_rets(from.rets());
    }
    if (from.has_oldrets()) {
      set_oldrets(from.oldrets());
    }
    if (from.has_oldxpos()) {
      set_oldxpos(from.oldxpos());
    }
    if (from.has_oldypos()) {
      set_oldypos(from.oldypos());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ServerFiveInt::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ServerFiveInt::CopyFrom(const ServerFiveInt& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerFiveInt::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void ServerFiveInt::Swap(ServerFiveInt* other) {
  if (other != this) {
    std::swap(retf_, other->retf_);
    std::swap(rets_, other->rets_);
    std::swap(oldrets_, other->oldrets_);
    std::swap(oldxpos_, other->oldxpos_);
    std::swap(oldypos_, other->oldypos_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ServerFiveInt::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ServerFiveInt_descriptor_;
  metadata.reflection = ServerFiveInt_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ServerReturn

// @@protoc_insertion_point(global_scope)
