// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerReturn4Int.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ServerReturn4Int.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ServerReturn {

namespace {

const ::google::protobuf::Descriptor* ServerFourInt_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ServerFourInt_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ServerReturn4Int_2eproto() {
  protobuf_AddDesc_ServerReturn4Int_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ServerReturn4Int.proto");
  GOOGLE_CHECK(file != NULL);
  ServerFourInt_descriptor_ = file->message_type(0);
  static const int ServerFourInt_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFourInt, retf_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFourInt, rets_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFourInt, rett_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFourInt, retfo_),
  };
  ServerFourInt_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ServerFourInt_descriptor_,
      ServerFourInt::default_instance_,
      ServerFourInt_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFourInt, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ServerFourInt, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ServerFourInt));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ServerReturn4Int_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ServerFourInt_descriptor_, &ServerFourInt::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ServerReturn4Int_2eproto() {
  delete ServerFourInt::default_instance_;
  delete ServerFourInt_reflection_;
}

void protobuf_AddDesc_ServerReturn4Int_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\026ServerReturn4Int.proto\022\014ServerReturn\"Q"
    "\n\rServerFourInt\022\014\n\004retf\030\001 \002(\003\022\017\n\004rets\030\002 "
    "\001(\003:\0010\022\017\n\004rett\030\003 \001(\003:\0010\022\020\n\005retfo\030\004 \001(\003:\001"
    "0", 121);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ServerReturn4Int.proto", &protobuf_RegisterTypes);
  ServerFourInt::default_instance_ = new ServerFourInt();
  ServerFourInt::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ServerReturn4Int_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ServerReturn4Int_2eproto {
  StaticDescriptorInitializer_ServerReturn4Int_2eproto() {
    protobuf_AddDesc_ServerReturn4Int_2eproto();
  }
} static_descriptor_initializer_ServerReturn4Int_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ServerFourInt::kRetfFieldNumber;
const int ServerFourInt::kRetsFieldNumber;
const int ServerFourInt::kRettFieldNumber;
const int ServerFourInt::kRetfoFieldNumber;
#endif  // !_MSC_VER

ServerFourInt::ServerFourInt()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ServerReturn.ServerFourInt)
}

void ServerFourInt::InitAsDefaultInstance() {
}

ServerFourInt::ServerFourInt(const ServerFourInt& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ServerReturn.ServerFourInt)
}

void ServerFourInt::SharedCtor() {
  _cached_size_ = 0;
  retf_ = GOOGLE_LONGLONG(0);
  rets_ = GOOGLE_LONGLONG(0);
  rett_ = GOOGLE_LONGLONG(0);
  retfo_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ServerFourInt::~ServerFourInt() {
  // @@protoc_insertion_point(destructor:ServerReturn.ServerFourInt)
  SharedDtor();
}

void ServerFourInt::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ServerFourInt::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ServerFourInt::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ServerFourInt_descriptor_;
}

const ServerFourInt& ServerFourInt::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ServerReturn4Int_2eproto();
  return *default_instance_;
}

ServerFourInt* ServerFourInt::default_instance_ = NULL;

ServerFourInt* ServerFourInt::New() const {
  return new ServerFourInt;
}

void ServerFourInt::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<ServerFourInt*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(retf_, retfo_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ServerFourInt::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ServerReturn.ServerFourInt)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 retf = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &retf_)));
          set_has_retf();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_rets;
        break;
      }

      // optional int64 rets = 2 [default = 0];
      case 2: {
        if (tag == 16) {
         parse_rets:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &rets_)));
          set_has_rets();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_rett;
        break;
      }

      // optional int64 rett = 3 [default = 0];
      case 3: {
        if (tag == 24) {
         parse_rett:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &rett_)));
          set_has_rett();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_retfo;
        break;
      }

      // optional int64 retfo = 4 [default = 0];
      case 4: {
        if (tag == 32) {
         parse_retfo:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &retfo_)));
          set_has_retfo();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ServerReturn.ServerFourInt)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ServerReturn.ServerFourInt)
  return false;
#undef DO_
}

void ServerFourInt::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ServerReturn.ServerFourInt)
  // required int64 retf = 1;
  if (has_retf()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->retf(), output);
  }

  // optional int64 rets = 2 [default = 0];
  if (has_rets()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->rets(), output);
  }

  // optional int64 rett = 3 [default = 0];
  if (has_rett()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->rett(), output);
  }

  // optional int64 retfo = 4 [default = 0];
  if (has_retfo()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->retfo(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ServerReturn.ServerFourInt)
}

::google::protobuf::uint8* ServerFourInt::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ServerReturn.ServerFourInt)
  // required int64 retf = 1;
  if (has_retf()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->retf(), target);
  }

  // optional int64 rets = 2 [default = 0];
  if (has_rets()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->rets(), target);
  }

  // optional int64 rett = 3 [default = 0];
  if (has_rett()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->rett(), target);
  }

  // optional int64 retfo = 4 [default = 0];
  if (has_retfo()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->retfo(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ServerReturn.ServerFourInt)
  return target;
}

int ServerFourInt::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 retf = 1;
    if (has_retf()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->retf());
    }

    // optional int64 rets = 2 [default = 0];
    if (has_rets()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->rets());
    }

    // optional int64 rett = 3 [default = 0];
    if (has_rett()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->rett());
    }

    // optional int64 retfo = 4 [default = 0];
    if (has_retfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->retfo());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ServerFourInt::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ServerFourInt* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ServerFourInt*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ServerFourInt::MergeFrom(const ServerFourInt& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_retf()) {
      set_retf(from.retf());
    }
    if (from.has_rets()) {
      set_rets(from.rets());
    }
    if (from.has_rett()) {
      set_rett(from.rett());
    }
    if (from.has_retfo()) {
      set_retfo(from.retfo());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ServerFourInt::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ServerFourInt::CopyFrom(const ServerFourInt& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerFourInt::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void ServerFourInt::Swap(ServerFourInt* other) {
  if (other != this) {
    std::swap(retf_, other->retf_);
    std::swap(rets_, other->rets_);
    std::swap(rett_, other->rett_);
    std::swap(retfo_, other->retfo_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ServerFourInt::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ServerFourInt_descriptor_;
  metadata.reflection = ServerFourInt_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ServerReturn

// @@protoc_insertion_point(global_scope)
